### ISSUE TITLE
Not working in new version on MacOS

### ISSUE THREAD

**Issue by NvL-WEAP** [mherrmann/ArrowNavigation#2] opened 2017-12-05 12:27 UTC
Since the new release 0.7.4 the ArrowNavigation plugin isn't working anymore. Probably due the change of path structure and added zip feature.

> Previously, files were located by their path, say C:\test.txt. This has now become file://C:/test.txt.

installation error:
```
Command 'InstallPlugin' raised error.

Traceback (most recent call last):
  File "fman/impl/plugins/plugin.py", line 270, in _run_in_thread
  File "/Applications/fman.app/Contents/Resources/Plugins/Core/core/commands.py", line 1165, in __call__
    dest_dir = self._install_plugin(repo.name, zipball_contents)
  File "/Applications/fman.app/Contents/Resources/Plugins/Core/core/commands.py", line 1199, in _install_plugin
    dir_in_zip, = iterdir(zip_url)
  File "fman/impl/util/__init__.py", line 137, in __next__
  File "fman/impl/util/__init__.py", line 114, in get_next
  File "fman/impl/util/__init__.py", line 118, in _generate_next
  File "/Applications/fman.app/Contents/Resources/Plugins/Core/core/fs/zip.py", line 46, in iterdir
    for candidate in self._iter_names(zip_path, path_in_zip):
  File "/Applications/fman.app/Contents/Resources/Plugins/Core/core/fs/zip.py", line 235, in _iter_names
    for file_info in self._iter_infos(zip_path, path_in_zip):
  File "/Applications/fman.app/Contents/Resources/Plugins/Core/core/fs/zip.py", line 247, in _iter_infos
    raise filenotfounderror(url)
FileNotFoundError: [Errno 2] No such file or directory: 'zip:///var/folders/6r/rf3yfzqd6js8c1p3s7bmz5hc0000gn/T/tmp8luadj51/plugin.zip/'
```

**Comment by mherrmann** [comment] 2017-12-05 13:03
I unfortunately cannot reproduce this bug (`ArrowNavigation` installs just fine for me on macOS). What's very strange is the path in the `FileNotFoundError` you posted: It ends with a slash `/`, that is, `.../plugin.zip/` instead of `.../plugin.zip`. I have no idea how that can happen.

Does the problem persist when you restart your computer and try again?

**Comment by NvL-WEAP** [comment] 2017-12-05 13:24
@mherrmann thank you for the quick response. A restart doesn't help.

Today i got a pop-up in fman that it has been updated and some plugins may be affected due the change of path management.

In a few hours i'm back at my office, and i'll check my iMac aswel.

**Comment by mherrmann** [comment] 2017-12-05 13:27
So you uninstalled ArrowNavigation with fman's `Remove plugin` command, then re-installed it with `Install plugin`?

**Comment by mherrmann** [comment] 2017-12-05 13:39
Let's continue this discussion [on the issue tracker of fman](https://github.com/fman-users/fman/issues/257) please. Closing this issue.

**Closed as completed by mherrmann** 2017-12-05 13:39 UTC
